### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by nateraw** [THUDM/CogView2#1]
The readme mentions that you should `pip install -r requirements.txt`, but this file isn't in the repo. It would be great if we could add that 😄

**Comment by Sleepychord** [comment]
Sorry for forgetting it! I just add a requirements.txt.

**Comment by nateraw** [comment]
Thank you! I noticed earlier that I had to have apex installed when I went to run the prediction code. Does icetk install it somewhere deeper in its deps or is this dep still missing?

**Comment by Sleepychord** [comment]
Hi @nateraw , I just made the apex (required in SwissArmyTransformer) optional. Please retry by upgrading it to `0.2.3`. In this way we cannot use fused_layer_norm.
