### ISSUE TITLE
which coglm.zip should be downloaded?

### ISSUE THREAD

**Issue by foobarhe** [THUDM/CogView2#11]
`You can download from [here](https://model.baai.ac.cn/model-detail/100041) and place them (folders named coglm/cogview2-dsr/cogview2-itersr) under SAT_HOME.`

There are 3 zip files, the script says should download coglm.zip but the text above looks we should download cogview2-itersr.zip?

**Comment by Sleepychord** [comment]
You should download all of them. The scripts should also automatically download them!
