### ISSUE TITLE
New error condition - Replicate interface frozen.

### ISSUE THREAD

**Issue by dza6549** [THUDM/CogView2#13]
Hello
It looks like the run has frozen. The wheels are spinning but the display has not moved for 7 minutes. Thank you
![Capture](https://user-images.githubusercontent.com/27390320/174560960-5e1079d7-9c10-4069-9ab8-4fe8fc35ac3c.PNG)

**Comment by chenxwh** [comment]
It’s downloading the ice_image.pt, some gpu instances might have worse internet connection sometimes, please try again
________________________________
From: dza6549 ***@***.***>
Sent: Monday, June 20, 2022 10:38:16 AM
To: THUDM/CogView2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [THUDM/CogView2] New error condition - Replicate interface frozen. (Issue #13)


Hello
It looks like the run has frozen. The wheels are spinning but the display has not moved for 7 minutes. Thank you
[Capture]<https://user-images.githubusercontent.com/27390320/174560960-5e1079d7-9c10-4069-9ab8-4fe8fc35ac3c.PNG>

**Comment by dza6549** [comment]
Thank you, worked again.
