### ISSUE TITLE
Model download link not working 

### ISSUE THREAD

**Issue by Deadsec69** [THUDM/CogView2#17]
Hi Model download link is not working taking too much time do anyone have alternative links

**Comment by Deadsec69** [comment]
I am using this code 
from baai_modelhub import AutoPull
auto_pull = AutoPull()
auto_pull.get_model(model_name='cogview2-ch',
                    model_save_path='./checkpoints/'
                    )

**Comment by Deadsec69** [comment]
got it have to download them one by one otherwise will get timeout

**Comment by eslambakr** [comment]
Hi @Deadsec69 

What do u mean by one by one can u specify more please?

Thanks in advance!

**Comment by liujingwen-bmil** [comment]
> I am using this code from baai_modelhub import AutoPull auto_pull = AutoPull() auto_pull.get_model(model_name='cogview2-ch', model_save_path='./checkpoints/' )

Hello！Have you solved this question and downloaded these files?
