### ISSUE TITLE
Uploading pretrained models to Hugging Face Hub

### ISSUE THREAD

**Issue by hysts** [THUDM/CogView2#18]
First of all, awesome work, and thank you for making the pretrained models publicly available.

My question is about redistribution of the models. Is it OK to make your pretrained models publicly available through Hugging Face Hub?

I've made [this gradio demo app for CogView2](https://github.com/hysts/CogView2_demo) and am currently working on make the app available on Hugging Face Space. To speed up the downloading time, I've uploaded the models in a private repo. Since the repo is private, I'm the only one who can download them from it for now. But I think it'd be appreciated to make it publicly available as a second source of download.

**Comment by Sleepychord** [comment]
Great, but please make sure there is a link pointing the this official repo in your readme.md and follow the Apache 2.0 license if needed.

**Comment by hysts** [comment]
Got it. Thank you!
