### ISSUE TITLE
`cd Image-Local-Attention && python setup.py install` does not work

### ISSUE THREAD

**Issue by tejas-gokhale** [THUDM/CogView2#22]
Thanks for uploading the code.  I am able to run the inference code using `--only-first-stage`.  However, I'm unable to run the whole model because the local attention kernel installation does not work.

Previously, it gave me an error saying my GCC version was too old. (needs to be 5 or higher, and 8 or lower)
When I updated GCC, it throws a long error trace with the two main errors being:

`FAILED: ./CogView2/Image-Local-Attention/build/temp.linux-x86_64-3.10/src/weighting.o`

`raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.` 

Could you specify which gcc version you used?

**Comment by hysts** [comment]
@tejas-gokhale In my case, the build was successful with `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`.
By the way, you might be interested in a demo app I made if you want to try CogView2. https://github.com/hysts/CogView2_demo

**Comment by tejas-gokhale** [comment]
thanks @hysts ! `gcc 7.5.0` solved the installation problem! And the image generation code works now :) Closing issue.

**Comment by tejas-gokhale** [comment]
thanks @hysts ! `gcc 7.5.0` solved the installation problem! And the image generation code works now :) Closing issue.
