### ISSUE TITLE
ValueError: temporally not support pure image samples

### ISSUE THREAD

**Issue by Molly260** [THUDM/CogView2#23]
When I run the pretrain_coglm.py use my own dataset made by cogdata, this error occurred while training the fifth epoch. 
The setting of cogdata is: cogdata create_task --description test --task_type IcetkImageTextTask --saver_type BinarySaver --length_per_sample 512 --img_sizes 256 --txt_len 111 --dtype int32 --model_path="/home/.icetk_models" test_task

**Comment by Sleepychord** [comment]
which error? seems not uploaded successfully.

**Comment by Molly260** [comment]
I use cogdata to tokenize text-image pair,  each image has a text, but when I use it to pretrain coglm, this error occurs:

tokens, position_ids, labels, attention_mask, loss_mask = get_batch(
  File "pretrain_coglm.py", line 61, in get_batch
    raise ValueError('temporally not support pure image samples')
ValueError: temporally not support pure image samples
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
  File "pretrain_coglm.py", line 211, in forward_step
    tokens, position_ids, labels, attention_mask, loss_mask = get_batch(
  File "pretrain_coglm.py", line 61, in get_batch
    raise ValueError('temporally not support pure image samples')

**Comment by victorup** [comment]
@Molly260 

> I use cogdata to tokenize text-image pair, each image has a text, but when I use it to pretrain coglm, this error occurs:
> 
> tokens, position_ids, labels, attention_mask, loss_mask = get_batch( File "pretrain_coglm.py", line 61, in get_batch raise ValueError('temporally not support pure image samples') ValueError: temporally not support pure image samples forward_ret = forward_step(data_iterator, model, args, timers, **kwargs) File "pretrain_coglm.py", line 211, in forward_step tokens, position_ids, labels, attention_mask, loss_mask = get_batch( File "pretrain_coglm.py", line 61, in get_batch raise ValueError('temporally not support pure image samples')

Hi, I encountered the same problem. How do you solve it?

**Comment by victorup** [comment]
> I use cogdata to tokenize text-image pair, each image has a text, but when I use it to pretrain coglm, this error occurs:
> 
> tokens, position_ids, labels, attention_mask, loss_mask = get_batch( File "pretrain_coglm.py", line 61, in get_batch raise ValueError('temporally not support pure image samples') ValueError: temporally not support pure image samples forward_ret = forward_step(data_iterator, model, args, timers, **kwargs) File "pretrain_coglm.py", line 211, in forward_step tokens, position_ids, labels, attention_mask, loss_mask = get_batch( File "pretrain_coglm.py", line 61, in get_batch raise ValueError('temporally not support pure image samples')

@Molly260 Hi, I encountered the same problem. How do you solve it?
