### ISSUE TITLE
Save individual frames 

### ISSUE THREAD

**Issue by Limbicnation** [THUDM/CogView2#24]
Hi, I was wondering how to save individual frames when using the `--only-first-stage` flag.
Thanks!

**Comment by Sleepychord** [comment]
Please use `--with-id`. When it toggled, you must specify an "id" before each input, e.g. 001\t一个漂亮的女孩, \t denoting TAB (NOT space). It will generate batch-size split images in a folder named "id" for each input. Confict with --debug.

**Comment by Limbicnation** [comment]
That worked. Many thanks!
