### ISSUE TITLE
Model download and GPU

### ISSUE THREAD

**Issue by metaphorz** [THUDM/CogView2#3]
I clicked on the hyperlinked "here" to download the model and it times out. My plan is to make a quick Colab Notebook. Related: on the GPU, you say to use an A100. With Google's Pro+ account, I usually get a V100 with 16gb memory. Is this enough? I do occasionally get an A100 but not often.

**Comment by ftaker887** [comment]
> I clicked on the hyperlinked "here" to download the model and it times out. My plan is to make a quick Colab Notebook. Related: on the GPU, you say to use an A100. With Google's Pro+ account, I usually get a V100 with 16gb memory. Is this enough? I do occasionally get an A100 but not often.

You probably need a minimum of 40GB of GPU memory. A 3090  is unable to run this even on a batch size of 1.
