### ISSUE TITLE
Can`t run on GPU

### ISSUE THREAD

**Issue by andriyrizhiy** [THUDM/CogView2#8]
Hello! Work looks awesome! But I can`t run it on my GPU. I have Nvidia 3060 with 12 GB space but have RuntimeError: CUDA out of memory. I tried to use --max-inference-batch-size 1 and --only-first-stage but it doesn't help me. Anyone can help me? Or prompt me how to run it on CPU

**Comment by vvvm23** [comment]
according to issue #3, you'll need about 40GB of GPU memory, even with an inference batch size of 1. The same issue says with `--only-first-stage` you might be able to use a 16GB GPU. So I think with 12GB you won't have much luck.

**Comment by Sleepychord** [comment]
@andriyrizhiy Hi, I am afraid that I cannot help more because the models are super large. The fp16 parameters of coglm has already 10GB. Maybe we will shrink the model in our works in the future but the CogView2 is that big. QAQ

**Comment by chenxwh** [comment]
@andriyrizhiy @vvvm23 Here is Replicate demo that is backed with A100 if you are interested :) https://replicate.com/thudm/cogview2

**Comment by andriyrizhiy** [comment]
Wow! Thank you, I see that you create a demo for text2image, are you planning to create a demo for text_guided_completion version?

**Comment by loboere** [comment]
replicate fails after some images

CUDA out of memory. Tried to allocate 1.22 GiB (GPU 0; 39.59 GiB total capacity; 30.86 GiB already allocated; 1.07 GiB free; 34.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
